name: Publish UpdateRunbook

on: 
    push:
        paths:
            - 'Modules/UpdateRunbookContent/**'
jobs:
    build:
      name: Publish
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v7
        - name: Publish
          env:
            APIKEY: ${{ secrets.POSH_GALLERY_API_KEY }}
          run: ./Modules/Publish.ps1 -TargetFolder "UpdateRunbookContent"
          shell: pwsh